---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbtools
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: downloads

  values:
    controllers:
      reannounce:
        containers:
          app:
            image:
              repository: ghcr.io/buroa/qbtools
              tag: v0.19.5
            env:
              TZ: ${TIMEZONE}
            args:
              [
                "reannounce",
                "--process-seeding",
                "--server",
                "qbittorrent.${SECRET_DOMAIN}",
                "--port",
                "80",
              ]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256M
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1030
        runAsGroup: 100
        seccompProfile: { type: RuntimeDefault }
