---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-addons-controller-manager
  namespace: flux-system
spec:
  path: ./deploy/controller
  prune: false
  sourceRef:
    kind: GitRepository
    name: kubernetes-csi-addons
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
