---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: minio-secret
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: &key d572f8f8-7927-4359-a427-ec6aa7ff2fbc
        property: access-key
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: *key
        property: secret-key
