---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: immich-server
      namespace: media

  values:
    controllers:
      immich-machine-learning:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.100.0@sha256:612e8856ad92f5915ececd5a67b76b7218f0fe4e41c72fcf1675bee76802294b

            env:
              DB_HOSTNAME: "immich-db-rw.media.svc.cluster.local"
              DB_DATABASE_NAME: "immich"
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-app
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-app
                    key: password

            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap

    service:
      app:
        controller: immich-machine-learning
        ports:
          http:
            port: 3003

    defaultPodOptions:
      securityContext:
        runAsUser: 1030
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      library:
        type: persistentVolumeClaim
        existingClaim: photos
        globalMounts:
          - path: /usr/src/app/upload
      cache:
        type: emptyDir
      transformers-cache:
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/.transformers_cache

    resources:
      requests:
        cpu: 5m
        memory: 274M
