apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FPYXNzoLRweWCZbf8j5kfLf0S4rVsdu/e2LmcYvC11iErU1a,iv:uhN71XpknMhmmMogU/70TOZuN5odhNe7+e+HaU+bYzY=,tag:3YaBn06Ldz4d9osCnmSYHA==,type:str]
    credentials.json: ENC[AES256_GCM,data:W15yb2e4CYjN6I1OBwYLcDu3q/aLQczyRo7W7KnoJiJ8PoELnsgqhoFx8sjzi2tI+PS7W9D9rDAeYTMeP2oXWwJfHFjdjaF5FTTk7QBC8gIwOdM5zyinDJSx7kM1aRHPsnEboOqiEMyxlaA++H2fNu8tj+7YH04GHATFTnmAAKPwmUlzYZo7vhH0Db5PCeKy+AGAAarPAmBsJxMPx+4+t+QEXksJx7Mo9e2pfnOa5g==,iv:HC/PaeJaoq0TYT7Jvn/NpgtoFoX6RqCKTzG0tItQFOo=,tag:SGf/pI/ZxhilkIw25yMfPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2REpJSklmQk9IWE5RcTVN
            dVgzYklDUzR5WVFMRVBjRUl6TEd2Rk9QTVN3CkJXcExGejg1Wi9CYlhSdDRZMXBP
            TFRHbmxvUllpN0hjZE9nRHBDKzYzeE0KLS0tIHhCcjc3Y0NtSmlzbms0TDFHQXFV
            VjBCbVFtd05DYkFwUTRQUkRtZElnMEEKoKBhoqAou40yJzrw5H6kwOHW0cXTAVwu
            Xp8O0/+jpp7uIXVCqDG/1EsFTGyFqVzoG9lL6R1UJiFWYEPKLI5pwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-18T21:19:38Z"
    mac: ENC[AES256_GCM,data:63n5DLL28JYZ9g/vCo0SWLUmXaHmHJqjiT7362DgLcsm3HTaURw6qw5eGkhxX7BQj3Z5flVsoCwe59Rlz1XWIXZUIbcAfB69JSVXTa5RF8siBizorFpLG9XGpHMWYjPIVpz0SOsIZ1N7FxkdJLf/jsga2soqocUoNDYkFD4dt/I=,iv:bCewJqKpQlXsu3zeNctWr4tszd0T/LmSjez5T/hAEMs=,tag:C2wjjQ7dM5P3QSkT8WJ2RA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
