---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  reset:
    desc: Reset templated configuration files
    prompt: Reset templated configuration files... continue?
    cmds:
      - task: :kubernetes:.reset
      - task: :sops:.reset
      - task: :talos:.reset

  force-reset:
    desc: Reset repo back to HEAD
    prompt: Reset repo back to HEAD... continue?
    cmds:
      - task: reset
      - git reset --hard HEAD
      - git clean -f -d
      - git pull origin main
