---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gluetun
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: gluetun-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WIREGUARD_PRIVATE_KEY: '{{ index . "wireguard-private-key" }}'
        SERVER_HOSTNAMES: '{{ index . "server-hostnames" }}'
  data:
    - secretKey: wireguard-private-key
      remoteRef:
        key: &key 2b1c7432-57a5-434b-aed2-65a132f82dad
        property: wireguard-private-key
    - secretKey: server-hostnames
      remoteRef:
        key: *key
        property: hostnames
