---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: &key fb75a2c0-4a8a-4249-aa39-09919070c066
        property: username
    - secretKey: admin-password
      remoteRef:
        key: *key
        property: password
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: grafana-s3-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_ACCESS_KEY: "{{ .minio_postgres_access_key }}"
        S3_SECRET_KEY: "{{ .minio_postgres_secret_key }}"
  data:
    - secretKey: minio_postgres_access_key
      remoteRef:
        key: &s3-key 6d3f7d5f-70cb-428f-8024-1dcd245d25dc
        property: username
    - secretKey: minio_postgres_secret_key
      remoteRef:
        key: *s3-key
        property: password
