---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
data:
  DB_PORT: "5432"
  LOG_LEVEL: log
  NODE_ENV: "production"
  REDIS_HOSTNAME: dragonfly.database.svc.cluster.local
  REDIS_DBINDEX: "0"
  REDIS_PORT: "6379"
  TRANSFORMERS_CACHE: /usr/src/app/.transformers_cache
  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003
