---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-s3"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: "${APP}-volsync-s3"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ index . "repository-template" }}/${APP}'
        RESTIC_PASSWORD: '{{ index . "restic-password" }}'
        AWS_ACCESS_KEY_ID: '{{ index . "access-key" }}'
        AWS_SECRET_ACCESS_KEY: '{{ index . "secret-key" }}'
  data:
    - secretKey: repository-template
      remoteRef:
        key: &restic-key 15de10b0-d000-404b-a1de-a9c69f384dca
        property: repository-template
    - secretKey: restic-password
      remoteRef:
        key: *restic-key
        property: restic-password
    - secretKey: access-key
      remoteRef:
        key: &s3-key 0ac1af10-93b1-4be1-988e-144ed567e2cd
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: *s3-key
        property: secret-key
