---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prowlarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system

  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1030
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    controllers:
      prowlarr:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              # https://github.com/qdm12/gluetun/issues/2054
              tag: latest@sha256:b51035be5a412fe4a5f27ff0cb4414dbb14f7505e038a2bfe0c05c48e837aed4
            resources:
              requests:
                cpu: 10m
                memory: 78M
              limits:
                squat.ai/tun: "1"
                memory: 128M
            securityContext:
              readOnlyRootFilesystem: false
              runAsNonRoot: false
              runAsUser: 0
              capabilities:
                add:
                  - NET_ADMIN
            env:
              TZ: ${TIMEZONE}
              VPN_SERVICE_PROVIDER: nordvpn
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              DOT: off
              DNS_KEEP_NAMESERVER: on
              FIREWALL_INPUT_PORTS: "9696,9999"
              FIREWALL_OUTBOUND_SUBNETS: "192.168.1.0/24,10.0.0.0/8"
              HEALTH_SERVER_ADDRESS: ":9999"
              VERSION_INFORMATION: off
            envFrom:
              - secretRef:
                  name: gluetun-secret
            restartPolicy: Always
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 9999
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 9999
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  failureThreshold: 5

        containers:
          app:
            env:
              TZ: ${TIMEZONE}
              PROWLARR__APP__INSTANCENAME: Prowlarr
              PROWLARR__APP__THEME: dark
              PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
              PROWLARR__LOG__DBENABLED: "False"
              PROWLARR__LOG__LEVEL: debug
              PROWLARR__SERVER__PORT: &port 9696
              PROWLARR__UPDATE__BRANCH: develop
              PROWLARR__API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-secret
                    key: api-key
            image:
              repository: ghcr.io/onedr0p/prowlarr-develop
              tag: 1.24.3.4754@sha256:9c88257656e4ac893d692abf38a784c80ef1638eb99fae376bdb48f75498ce52
            resources:
              requests:
                memory: 200M
                cpu: 10m
              limits:
                memory: 500M
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: config-prowlarr
