---
apiVersion: v1
kind: Pod
metadata:
  name: ${job}
  namespace: default
spec:
  restartPolicy: Never
  nodeName: ${node}
  containers:
    - name: main
      image: busybox
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "dd if=/dev/zero bs=1M count=100 oflag=direct of=${disk}",
        ]
