apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:hqiuo8bgeqmDnalatHdM+qzweMIB44sjaXGklcjBTf8=,iv:Oug3uIFAOdd/MxxLMJx4LZ029xz6ra1meYIORST9OPg=,tag:b0GwSJA/TrXvSqDnJQu7Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdXc4WGZQUGV6c0VQSVZE
            NFplQzZaWHdVTU1yYWlXbzZtK3RBd2JZTWcwCldMTkhBSlY5NDR5SHdWK0xaTWxp
            ZzdFK3pXMlhiV1ltbUJJMHpHZ2lOcVUKLS0tIDVuS2I1V2F2S0FUSjB4UHpuUlNF
            TXQvMWFBbVUvckQzUTNRZUc4S3JlV1UK3cLdt56DSx0xZ9g1ccr/6DLYpoKc9Q/w
            IiJfTzCC0+Ii8arOGxvoe33ZR8yv0qQWVltLT7QMh5f+dp6dX+7sxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-18T21:19:38Z"
    mac: ENC[AES256_GCM,data:TfAFrsFnC13sFi5uzNz1EvmAlCh9+wib3BSmEqsUbH5Gq8v6oAgusj6XzSvIeUD7uJsBJ1pwdJu8XDgzOn9Oxyp+eW94eaBvhuJRADRBdl+fr+fR28RFw43QMiTO8e/Z6pUd3Fi+fcYkW8KQG8UI6XCK/wkUpx/1hu+Yi6iQ62g=,iv:s6WsVoLL2nhCaL+NS2Rjek8Fl1iPGnSQs0UgLwg+kMA=,tag:l5UKbR7cYljH5IHOcwBBAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
