---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      tailscale:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.74.1@sha256:a013ce5266e5c796efe31c7cf9562deb21423f8586361d7faadaf675fa4296ac
            env:
              TZ: ${TIMEZONE}
              NO_AUTOUPDATE: true
              PORT: &port ${SECRET_TAILSCALE_PORT}
              TS_KUBE_SECRET: ""
              SA_NAME: tailscale
              TS_USERSPACE: true
              TS_ROUTES: "192.168.1.0/24"
              TS_EXTRA_ARGS: "--advertise-exit-node"
              TS_TAILSCALED_EXTRA_ARGS: --debug=0.0.0.0:9001
              TS_STATE_DIR: &path /tmp
              TS_HOSTNAME:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            envFrom:
              - secretRef:
                  name: tailscale-auth
            resources:
              requests:
                cpu: 10m
                memory: 50M
              limits:
                memory: 278M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app

    persistence:
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      tmp:
        type: emptyDir
        globalMounts:
          - path: *path

    service:
      app:
        controller: *app
        nameOverride: *app
        ports:
          http:
            port: 9001
      tailnet:
        controller: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.1.224"
        ports:
          tailnet:
            port: *port
            protocol: UDP

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /debug/metrics
            interval: 1m
            scrapeTimeout: 10s
