---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-ceph-dashboard
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: rook-ceph-dashboard-password # rook-ceph expects this name
    template:
      engineVersion: v2
      data:
        password: "{{ .rook_dashboard_password }}"

  data:
    - secretKey: rook_dashboard_password
      remoteRef:
        key: bc2dee75-ec26-41b0-82e9-b3232daaa342
        property: password
