---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      bitwarden:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          cli:
            image:
              repository: ghcr.io/larivierec/bitwarden-cli
              tag: 2024.8.1@sha256:639a6c14a346706e48d7ab264fd62a965fc5e1afbdcd47a7723ee1ed8bf42639
            envFrom:
              - secretRef:
                  name: bitwarden-cli
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      [
                        "sh",
                        "-c",
                        "curl -X POST -s http://127.0.0.1:8087/sync | jq -e '.success == true'",
                      ]
                  initialDelaySeconds: 15
                  timeoutSeconds: 5
                  periodSeconds: 30
                  failureThreshold: 3

              readiness:
                enabled: false

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256M
    service:
      cli:
        controller: bitwarden
        ports:
          http:
            port: 8087
