---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./networkpolicy.yaml
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/instance: downloads-gateway
  app.kubernetes.io/name: pod-gateway
