---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-minio"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: "${APP}-volsync-minio"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ index . "repository-template" }}/${APP}'
        RESTIC_PASSWORD: '{{ index . "restic-password" }}'
        AWS_ACCESS_KEY_ID: '{{ index . "access-key" }}'
        AWS_SECRET_ACCESS_KEY: '{{ index . "secret-key" }}'
  data:
    - secretKey: repository-template
      remoteRef:
        key: &restic-key 2ec2b424-eb72-46eb-9946-7b83a370d3bd
        property: repository-template
    - secretKey: restic-password
      remoteRef:
        key: *restic-key
        property: restic-password
    - secretKey: access-key
      remoteRef:
        key: &minio-key d572f8f8-7927-4359-a427-ec6aa7ff2fbc
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: *minio-key
        property: secret-key
